### ISSUE TITLE
Doesn't seem to work for 60.1.0esr (64-bit)

### ISSUE THREAD

**Issue by DeathStalker77** [pratyushtewari/firefox-like-chrome#1]
Followed the instructions, but still have the same rectangular tabs :(

**Comment by pratyushtewari** [comment]
I don't think I tested on that version but it sure works on 63.0.3 (64-bit)

**Comment by pratyushtewari** [comment]
When Firefox updates, it might replace the custom css file with a default one. If this theme has stopped working for you, try adding the css file to the root folder again.
