### ISSUE TITLE
Tab color on hover and tab minimum width

### ISSUE THREAD

**Issue by Tumleren** [pratyushtewari/firefox-like-chrome#10]
Hi, I'm trying to change the tab color on hover with no luck at the moment. I'm looking to get it to rgb(177, 178, 184), but I can't work out what's going on, it seems like the tab goes transparent on hover.

I'm also after adjusting the minimum width of the tabs as it's currently unreadable
Any help appreciated

**Comment by pratyushtewari** [comment]
Hi @Tumleren, I have not checked this repo for some time and I might need to check it out again and will take some time. meanwhile if you have any PR then please send one and I'll merge it.

**Comment by lcheylus** [comment]
> I'm also after adjusting the minimum width of the tabs as it's currently unreadable.

To modify minimum width for tabs, see `about:config` => `browser.tabs.tabMinWidth` and change the value according to your needs (personally I set it to 110 ).

**Comment by pratyushtewari** [comment]
Sure. Can you send me a pull request?
