### ISSUE TITLE
corners are not sharp

### ISSUE THREAD

**Issue by luna800** [pratyushtewari/firefox-like-chrome#3]
Hello,
the corners of the tabs are not sharp 
![fasdfdure](https://user-images.githubusercontent.com/45806421/49841389-b7d78f00-fdb7-11e8-9a16-2eeb8f429107.PNG)

**Comment by luna800** [comment]
I found a workaround:

add `outline: 1px solid transparent;` to `.tab-background`

**Comment by Thespikedballofdoom** [comment]
thank you so much!
