### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by dackdel** [pratyushtewari/firefox-like-chrome#6]
this isint working for linux. are there different steps?

**Comment by pratyushtewari** [comment]
Oh! I do not have a linux setup to test right now. 🤔, Can you tell in more details, what step from the readme file is not working. I'll try to find the steps for Linux somehow.

**Comment by dackdel** [comment]
my bad. got it working. there was more than one firefox installed so i was changing the files on the wrong one. fixed it. works great. but on hover the tabs turn white is that intentional 
![screenshot from 2019-02-04 02-24-24](https://user-images.githubusercontent.com/380951/52182535-210dd880-2824-11e9-9dbd-92814769b26c.png)

**Comment by pratyushtewari** [comment]
Great. The hover white: could be the default behavior of Firefox on Linux. I don't think I have added overrides to change the hover behavior. If you want you can try debugging the Firefox UI and then send a pull req. This, by the way, does not happen on my mac.

**Comment by pratyushtewari** [comment]
I am closing this issue, for now. since the original problem is solved.
