### ISSUE TITLE
New Tab Button (+) obscured in FireFox 70

### ISSUE THREAD

**Issue by ivan-kljajic** [pratyushtewari/firefox-like-chrome#7]
After upgrading to Firefox 70.0 I noticed the new tab button was obscured and hard to click.
I googled around and saw that a changeset checked into Firefox changed the CSS dealing with the new tab button slightly.
Anyway, I fixed this by changing my userChrome.css.

Old (userChrome.css line 52):
`.tabs-newtab-button.toolbarbutton-1 {
    margin-left: 20px !important;
  }`

New:
`#tabs-newtab-button {
    margin-left: 20px !important;
}`

**Comment by pratyushtewari** [comment]
I merged in to the master. Thank you!
